on:
  push:
    paths:
      - 'README.Rmd'

name: Render Rmarkdown files

jobs:
  render:
    name: Render Rmarkdown files
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # This is important to set for `git diff-tree` to work below
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and remotes
        run: |
          install.packages("remotes")
          remotes::install_cran("rmarkdown")
        shell: Rscript {0}
      - name: Render Rmarkdown files
        run: |
          RMD_PATH=($(git diff-tree --no-commit-id --name-only -r HEAD | grep '[.]Rmd$'))
          Rscript -e 'for (file in commandArgs(TRUE)) rmarkdown::render(file)' ${RMD_PATH[*]}
      - name: Commit results
        run: |
          git config --local user.email "derek.corcoran.barrios@gmail.com"
          git config --local user.name "derek-corcoran-barrios"
          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"